<?php
/**
 * LICENSE: This source file is subject to version 3.0 of the GPL license
 * that is available through the world-wide-web at the following URI:
 * https://www.gnu.org/licenses/gpl-3.0.fr.html (french version).
 *
 * @author      Guillaume Gagnaire <contact@42php.com>
 * @link        https://www.github.com/42php/42php
 * @license     https://www.gnu.org/licenses/gpl-3.0.fr.html GPL
 */

namespace                       Core;

/**
 * Contient la liste des pays avec leur code ISO.
 *
 * Class Countries
 * @package Core
 */
class                           Countries {
    /**
     * Retourne la liste des pays.
     *
     * @return array            La liste des pays
     */
    public static function      getList() {
        Debug::trace();
        return [
            'af' => _t('Afghanistan'),
            'za' => _t('Afrique du Sud'),
            'al' => _t('Albanie'),
            'dz' => _t('Algérie'),
            'de' => _t('Allemagne'),
            'ad' => _t('Andorre'),
            'ao' => _t('Angola'),
            'ai' => _t('Anguilla'),
            'aq' => _t('Antarctique'),
            'ag' => _t('Antigua-et-Barbuda'),
            'sa' => _t('Arabie saoudite'),
            'ar' => _t('Argentine'),
            'am' => _t('Arménie'),
            'aw' => _t('Aruba'),
            'au' => _t('Australie'),
            'at' => _t('Autriche'),
            'az' => _t('Azerbaïdjan'),
            'bs' => _t('Bahamas'),
            'bh' => _t('Bahreïn'),
            'bd' => _t('Bangladesh'),
            'bb' => _t('Barbade'),
            'be' => _t('Belgique'),
            'bz' => _t('Belize'),
            'bj' => _t('Bénin'),
            'bm' => _t('Bermudes'),
            'bt' => _t('Bhoutan'),
            'by' => _t('Biélorussie'),
            'bo' => _t('Bolivie'),
            'ba' => _t('Bosnie-Herzégovine'),
            'bw' => _t('Botswana'),
            'br' => _t('Brésil'),
            'bn' => _t('Brunéi Darussalam'),
            'bg' => _t('Bulgarie'),
            'bf' => _t('Burkina Faso'),
            'bi' => _t('Burundi'),
            'kh' => _t('Cambodge'),
            'cm' => _t('Cameroun'),
            'ca' => _t('Canada'),
            'cv' => _t('Cap-Vert'),
            'ea' => _t('Ceuta et Melilla'),
            'cl' => _t('Chili'),
            'cn' => _t('Chine'),
            'cy' => _t('Chypre'),
            'co' => _t('Colombie'),
            'km' => _t('Comores'),
            'cg' => _t('Congo-Brazzaville'),
            'cd' => _t('Congo-Kinshasa'),
            'kp' => _t('Corée du Nord'),
            'kr' => _t('Corée du Sud'),
            'cr' => _t('Costa Rica'),
            'ci' => _t('Côte d’Ivoire'),
            'hr' => _t('Croatie'),
            'cu' => _t('Cuba'),
            'cw' => _t('Curaçao'),
            'dk' => _t('Danemark'),
            'dg' => _t('Diego Garcia'),
            'dj' => _t('Djibouti'),
            'dm' => _t('Dominique'),
            'eg' => _t('Égypte'),
            'sv' => _t('El Salvador'),
            'ae' => _t('Émirats arabes unis'),
            'ec' => _t('Équateur'),
            'er' => _t('Érythrée'),
            'es' => _t('Espagne'),
            'ee' => _t('Estonie'),
            'va' => _t('État de la Cité du Vatican'),
            'fm' => _t('États fédérés de Micronésie'),
            'us' => _t('États-Unis'),
            'et' => _t('Éthiopie'),
            'fj' => _t('Fidji'),
            'fi' => _t('Finlande'),
            'fr' => _t('France'),
            'ga' => _t('Gabon'),
            'gm' => _t('Gambie'),
            'ge' => _t('Géorgie'),
            'gh' => _t('Ghana'),
            'gi' => _t('Gibraltar'),
            'gr' => _t('Grèce'),
            'gd' => _t('Grenade'),
            'gl' => _t('Groenland'),
            'gp' => _t('Guadeloupe'),
            'gu' => _t('Guam'),
            'gt' => _t('Guatemala'),
            'gg' => _t('Guernesey'),
            'gn' => _t('Guinée'),
            'gq' => _t('Guinée équatoriale'),
            'gw' => _t('Guinée-Bissau'),
            'gy' => _t('Guyana'),
            'gf' => _t('Guyane française'),
            'ht' => _t('Haïti'),
            'hn' => _t('Honduras'),
            'hu' => _t('Hongrie'),
            'cx' => _t('Île Christmas'),
            'ac' => _t('Île de l’Ascension'),
            'im' => _t('Île de Man'),
            'nf' => _t('Île Norfolk'),
            'ax' => _t('Îles Åland'),
            'ky' => _t('Îles Caïmans'),
            'ic' => _t('Îles Canaries'),
            'cc' => _t('Îles Cocos'),
            'ck' => _t('Îles Cook'),
            'fo' => _t('Îles Féroé'),
            'gs' => _t('Îles Géorgie du Sud et Sandwich du Sud'),
            'fk' => _t('Îles Malouines'),
            'mp' => _t('Îles Mariannes du Nord'),
            'mh' => _t('Îles Marshall'),
            'um' => _t('Îles mineures éloignées des États-Unis'),
            'sb' => _t('Îles Salomon'),
            'tc' => _t('Îles Turques-et-Caïques'),
            'vg' => _t('Îles Vierges britanniques'),
            'vi' => _t('Îles Vierges des États-Unis'),
            'in' => _t('Inde'),
            'id' => _t('Indonésie'),
            'iq' => _t('Irak'),
            'ir' => _t('Iran'),
            'ie' => _t('Irlande'),
            'is' => _t('Islande'),
            'il' => _t('Israël'),
            'it' => _t('Italie'),
            'jm' => _t('Jamaïque'),
            'jp' => _t('Japon'),
            'je' => _t('Jersey'),
            'jo' => _t('Jordanie'),
            'kz' => _t('Kazakhstan'),
            'ke' => _t('Kenya'),
            'kg' => _t('Kirghizistan'),
            'ki' => _t('Kiribati'),
            'xk' => _t('Kosovo'),
            'kw' => _t('Koweït'),
            're' => _t('La Réunion'),
            'la' => _t('Laos'),
            'ls' => _t('Lesotho'),
            'lv' => _t('Lettonie'),
            'lb' => _t('Liban'),
            'lr' => _t('Libéria'),
            'ly' => _t('Libye'),
            'li' => _t('Liechtenstein'),
            'lt' => _t('Lituanie'),
            'lu' => _t('Luxembourg'),
            'mk' => _t('Macédoine'),
            'mg' => _t('Madagascar'),
            'my' => _t('Malaisie'),
            'mw' => _t('Malawi'),
            'mv' => _t('Maldives'),
            'ml' => _t('Mali'),
            'mt' => _t('Malte'),
            'ma' => _t('Maroc'),
            'mq' => _t('Martinique'),
            'mu' => _t('Maurice'),
            'mr' => _t('Mauritanie'),
            'yt' => _t('Mayotte'),
            'mx' => _t('Mexique'),
            'md' => _t('Moldavie'),
            'mc' => _t('Monaco'),
            'mn' => _t('Mongolie'),
            'me' => _t('Monténégro'),
            'ms' => _t('Montserrat'),
            'mz' => _t('Mozambique'),
            'mm' => _t('Myanmar'),
            'na' => _t('Namibie'),
            'nr' => _t('Nauru'),
            'np' => _t('Népal'),
            'ni' => _t('Nicaragua'),
            'ne' => _t('Niger'),
            'ng' => _t('Nigéria'),
            'nu' => _t('Niue'),
            'no' => _t('Norvège'),
            'nc' => _t('Nouvelle-Calédonie'),
            'nz' => _t('Nouvelle-Zélande'),
            'om' => _t('Oman'),
            'ug' => _t('Ouganda'),
            'uz' => _t('Ouzbékistan'),
            'pk' => _t('Pakistan'),
            'pw' => _t('Palaos'),
            'pa' => _t('Panama'),
            'pg' => _t('Papouasie-Nouvelle-Guinée'),
            'py' => _t('Paraguay'),
            'nl' => _t('Pays-Bas'),
            'bq' => _t('Pays-Bas caribéens'),
            'pe' => _t('Pérou'),
            'ph' => _t('Philippines'),
            'pn' => _t('Pitcairn'),
            'pl' => _t('Pologne'),
            'pf' => _t('Polynésie française'),
            'pr' => _t('Porto Rico'),
            'pt' => _t('Portugal'),
            'qa' => _t('Qatar'),
            'hk' => _t('R.A.S. chinoise de Hong Kong'),
            'mo' => _t('R.A.S. chinoise de Macao'),
            'cf' => _t('République centrafricaine'),
            'do' => _t('République dominicaine'),
            'cz' => _t('République tchèque'),
            'ro' => _t('Roumanie'),
            'gb' => _t('Royaume-Uni'),
            'ru' => _t('Russie'),
            'rw' => _t('Rwanda'),
            'eh' => _t('Sahara occidental'),
            'bl' => _t('Saint-Barthélemy'),
            'kn' => _t('Saint-Christophe-et-Niévès'),
            'sm' => _t('Saint-Marin'),
            'mf' => _t('Saint-Martin (partie française)'),
            'sx' => _t('Saint-Martin (partie néerlandaise)'),
            'pm' => _t('Saint-Pierre-et-Miquelon'),
            'vc' => _t('Saint-Vincent-et-les-Grenadines'),
            'sh' => _t('Sainte-Hélène'),
            'lc' => _t('Sainte-Lucie'),
            'ws' => _t('Samoa'),
            'as' => _t('Samoa américaines'),
            'st' => _t('Sao Tomé-et-Principe'),
            'sn' => _t('Sénégal'),
            'rs' => _t('Serbie'),
            'sc' => _t('Seychelles'),
            'sl' => _t('Sierra Leone'),
            'sg' => _t('Singapour'),
            'sk' => _t('Slovaquie'),
            'si' => _t('Slovénie'),
            'so' => _t('Somalie'),
            'sd' => _t('Soudan'),
            'ss' => _t('Soudan du Sud'),
            'lk' => _t('Sri Lanka'),
            'se' => _t('Suède'),
            'ch' => _t('Suisse'),
            'sr' => _t('Suriname'),
            'sj' => _t('Svalbard et Jan Mayen'),
            'sz' => _t('Swaziland'),
            'sy' => _t('Syrie'),
            'tj' => _t('Tadjikistan'),
            'tw' => _t('Taïwan'),
            'tz' => _t('Tanzanie'),
            'td' => _t('Tchad'),
            'tf' => _t('Terres australes françaises'),
            'io' => _t('Territoire britannique de l’océan Indien'),
            'ps' => _t('Territoires palestiniens'),
            'th' => _t('Thaïlande'),
            'tl' => _t('Timor oriental'),
            'tg' => _t('Togo'),
            'tk' => _t('Tokelau'),
            'to' => _t('Tonga'),
            'tt' => _t('Trinité-et-Tobago'),
            'ta' => _t('Tristan da Cunha'),
            'tn' => _t('Tunisie'),
            'tm' => _t('Turkménistan'),
            'tr' => _t('Turquie'),
            'tv' => _t('Tuvalu'),
            'ua' => _t('Ukraine'),
            'uy' => _t('Uruguay'),
            'vu' => _t('Vanuatu'),
            've' => _t('Venezuela'),
            'vn' => _t('Vietnam'),
            'wf' => _t('Wallis-et-Futuna'),
            'ye' => _t('Yémen'),
            'zm' => _t('Zambie'),
            'zw' => _t('Zimbabwe')
        ];
    }
}